name: Integration Test Suite

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/integration-test.yml"
      - ".cargo/**"
      - "benches/**"
      - "lib/**"
      - "proto/**"
      - "scripts/**"
      - "skaffold/**"
      - "src/**"
      - "tests/**"
      - "build.rs"
      - "Cargo.lock"
      - "Cargo.toml"
      - "Makefile"
      - "rust-toolchain"
  pull_request:

env:
  AUTOINSTALL: true
  AWS_ACCESS_KEY_ID: "dummy"
  AWS_SECRET_ACCESS_KEY: "dummy"
  CONTAINER_TOOL: "docker"
  RUST_BACKTRACE: full
  RUST_TEST_THREADS: 1
  TEST_LOG: vector=debug
  VERBOSE: true
  CI: true
  PROFILE: debug

jobs:
  cancel-previous:
    name: Cancel redundant jobs
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    if: github.ref != 'refs/heads/master'
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          all_but_latest: true # can cancel workflows scheduled later

  test-integration:
    name: Integration - Linux, ${{ matrix.test }}
    runs-on: ubuntu-20.04
    if: |
      !github.event.pull_request
        || contains(github.event.pull_request.labels.*.name, 'ci-condition: integration tests enable')
    strategy:
      fail-fast: false
      matrix:
       include:
         - test: 'redis'
    steps:
      - uses: actions/checkout@v2.4.0
      - run: docker-compose -f scripts/integration/docker-compose.${{ matrix.test }}.yml run runner
      - run: docker-compose -f scripts/integration/docker-compose.${{ matrix.test }}.yml rm -fsv
        if: ${{ always() }}

  test-integration-check:
    name: test-integration-check
    runs-on: ubuntu-latest
    needs:
      - test-integration
    steps:
      - name: validate
        run: echo "OK"

  master-failure:
    name: master-failure
    if: failure() && github.ref == 'refs/heads/master'
    needs:
      - cancel-previous
      - test-integration-check
    runs-on: ubuntu-20.04
    steps:
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@0.3.2
      with:
        args: "Master integration tests failed: <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}>"
